### ISSUE TITLE
How to add group

### ISSUE THREAD

**Issue by hazhayder** [miguilimzero/filament-auto-panel#1]
I really like this particular Filament plugin created an admin panel in under 60 mins, The only problem I am facing at the moment is I am using SEO package https://filamentphp.com/plugins/ralphjsmit-seo which returns a SEO group how can I use that inside this?

**Comment by miguilimzero** [comment]
Hello @hazhaydez, you can try to extend the form function and customize it with the extra fields you want. Something like this (check the AutoResource class file for better understanding):

```php
public static function form(Form $form): Form
{
        return $form
            ->schema([
                SEO::make(), // Your custom field
                ...FormGenerator::make(
                        modelClass: static::getModel(), 
                        overwriteColumns: static::getColumnsOverwriteMapped('form'),
                        enumDictionary: static::$enumDictionary,
                )
        ])
        ->columns(2);
}
```

**Comment by hazhayder** [comment]
> Hello @hazhayder , you can try to extend the form function and customize it with the extra fields you want. Something like this (check the AutoResource class file for better understanding):
> 
> ```
> public static function form(Form $form): Form
> {
>         return $form
>             ->schema([
>                 SEO::make(), // Your custom field
>                 ...FormGenerator::make(
>                         modelClass: static::getModel(), 
>                         overwriteColumns: static::getColumnsOverwriteMapped('form'),
>                         enumDictionary: static::$enumDictionary,
>                 )
>         ])
>         ->columns(2);
> }
> ```

Thanks this worked

**Comment by Issa-projects** [comment]
I see, thank you
