### ISSUE TITLE
Can't get past composer  install step

### ISSUE THREAD

**Issue by musiccollect** [miguilimzero/filament-auto-panel#2]
All attempts to use "php artisan make:filament-auto-resource" result in the following error:

The "model-namespace" option does not exist. 

Laravel 10, Filament 3, any model name eg. Artist, Artists, Egg, Eggs etc...

**Comment by miguilimzero** [comment]
It seems filament introduced a new parameter called `model-namespace` and the auto-resource was outdated with the base resource command. It should be fixed by `1.4.2` version I just released.

**Comment by musiccollect** [comment]
Thanks, yep works perfectly now.
